name: Service Request-Generic
description: Request for information related to a project
labels: ["Type/ServiceRequest"]

body:
# Hidden marker field used for workflow validation
  - type: input
    id: template-marker
    attributes:
      label: "Template Marker"
      description: "Do not remove or modify. Used for validation."
      value: "SR Generic"
    validations:
      required: true

# Short Description (textarea)
  - type: textarea
    id: short_description
    attributes:
      label: Short Description
      description: Provide a brief description of the request
    validations:
      required: true
      
# Request Description (textarea)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide details of the change required
    validations:
      required: true

 
 